# -*- coding: utf-8 -*-
"""reddit scrape!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CG42p_iIyuHOy1a5n29xJTSm_YfTVbiZ
"""

pip install praw

import praw
import pickle
import time
from google.colab import drive

drive.mount('/content/drive')

# Step 1: Set up Reddit API credentials
reddit = praw.Reddit(client_id='g1B_Pdsfwszzw5xbUf3i3g',
                     client_secret='kZWNzy2Jje3gT32CHJrtf8p1Xdczow',
                     user_agent='test-script/1.0 by ak-gom')

# Step 2: Specify the keywords
keywords = ['healthcare', 'climate change', 'gun control']  # Add more specific keywords if necessary

# Step 3: Search for relevant subreddits
relevant_subreddits = []

for keyword in keywords:
    # Use the subreddit search functionality
    search_results = reddit.subreddits.search(keyword)

    # Extract subreddit names from search results
    for subreddit in search_results:
        relevant_subreddits.append(subreddit.display_name)

print("Relevant Subreddits:")
for subreddit_name in relevant_subreddits:
    print(subreddit_name)

# Step 4: Get relevant posts from each identified subreddit
relevant_postsa = []

for subreddit_name in relevant_subreddits:
    subreddit = reddit.subreddit(subreddit_name)
    print(f"Searching posts in subreddit: {subreddit_name}")

    x = 0
    for submission in subreddit.hot(limit=50):  # Adjust the limit as needed
        title = submission.title.lower()
        selftext = submission.selftext.lower()  # Your code here
        x += 1
        time.sleep(1)  # Add a delay of 1 second between requests

        # Print the post information as it searches
        print(f"Searching post {x} in subreddit {subreddit_name}:")
        print(f"Title: {title}")
        print(f"Selftext: {selftext}")

        # Check if title or selftext is not empty and also check for meaningful content
        if (title.strip() != '' or selftext.strip() != '') and any(
                keyword in title.lower() or keyword in selftext.lower() for keyword in keywords):
            relevant_postsa.append({
                'subreddit': subreddit_name,
                'title': submission.title,
                'url': submission.url,
                'text': submission.selftext
            })

            print("Relevant post found:")
            print(f"Title: {submission.title}")
            print(f"URL: {submission.url}")
            print(f"Text: {submission.selftext}")

# Step 5: Store the relevant data in a pickle file
pickle_file_path = '/content/drive/MyDrive/relevant_data.pickle'

with open(pickle_file_path, 'wb') as file:
    pickle.dump(relevant_postsa, file)

print(f"Data saved to {pickle_file_path}")

print(type(relevant_postsa))